name: awanderlustlifestyle
favicon: null
layout_spectrum: 0.42958
typography_spectrum: 0.995602905517444
title: A Wanderlust Lifestyle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e42692'
    - '#2f2bad'
    - '#ffffff'
    - '#ff0000'
    - '#706dc6'
  brandStrength: 0.5437028303276747
  lightness: 0.329110246617347
  saturation: 0.8244620384648442
  rhythmicContrast: 0
purpose: []
